### ISSUE TITLE
Suggestion: Peeping Skeletons

### ISSUE THREAD

**Issue by EmoBubbleGum** [Sindarin27/peeping-creepers#2]
I've seen skeletons in other mods using cover to their advantage, and peaking their heads out. I really love your mod as an AI difficulty mod, and think your mod could be the perfect improved AI mod that fabric is lacking in 1.17

Possible idea for zombies, have them call eachother and turn into a group if they spot a player. Or if you feel like going a little crazy, you could have them mount each other to climb to reach the player.

**Comment by Sindarin27** [comment]
I love these ideas! If I were to implement anything like this, they would likely be separate mods though. It'll also require me to learn a great deal more about pathfinding 😅
Closing the issue for now, but I'll keep you updated on whether I get anywhere with these ideas.
