### ISSUE TITLE
[Suggestion] Chase-Only Breach

### ISSUE THREAD

**Issue by RyanCR03** [Sindarin27/peeping-creepers#4]
Creepers will only breach through walls if they were already previously chasing you.
If you are in your house a lot then it would be annoying if a random creeper that spawns outside blows a hole in the side for no reason. 
It would make more sense for creepers to only breach walls if they were running away from them.
It would create more of a "you can run but you can't hide" situation.

**Comment by Sindarin27** [comment]
Theoretically, turning off the X-Ray setting in the config should already create this behaviour. If this is not the case, let me know and I'll take a deeper look into it!

**Comment by RyanCR03** [comment]
well yes theoretically but once you close the door they forget you exist

**Comment by Sindarin27** [comment]
Ah, like that. I think it should be possible to add a variation on the x-ray targeting I currently use, making it so that a creeper needs to see the player to start chasing. I will take a crack at it in due time.

**Comment by Sindarin27** [comment]
This is now implemented in the next 1.18 release of the mod, version 1.2 when it releases. The default settings keep the current behaviour, but x-ray behavior will be split between `xrayStartTargeting` and `xrayFollowTarget`.
